trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: 'HaoSubscriptionConn'      # your Azure DevOps service connection
  aksResourceGroup: 'devop-aks'    # resource group of AKS
  aksCluster: 'devop-aks'             # AKS cluster name
  namespace: 'dev'
  containerRegistry: 'devopacr.azurecr.io'
  tag: 'latest'

steps:
# 1️⃣ Checkout code
- task: Checkout@1
  displayName: 'Checkout code'

# 2️⃣ Connect to AKS
- task: AzureCLI@2
  displayName: 'Connect to AKS'
  inputs:
    azureSubscription: '$(azureSubscription)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az aks get-credentials --resource-group $(aksResourceGroup) --name $(aksCluster) --overwrite-existing
      kubectl config current-context

# 3️⃣ Deploy backend image to AKS
- script: |
    echo "Using registry: $(containerRegistry)"
    echo "Namespace: $(namespace)"

    # Create namespace if not exists
    kubectl get namespace $(namespace) || kubectl create namespace $(namespace)
    kubectl config set-context --current --namespace=$(namespace)

    echo "Deploying backend..."
    export REGISTRY=$(containerRegistry)
    envsubst < k8s_deployment/backend.yaml | kubectl apply -f -
  displayName: 'Deploy to AKS'

# 4️⃣ Verify deployment
- script: |
    kubectl get pods
    kubectl get svc
  displayName: 'Verify AKS deployment'
